import React, { createContext, useContext, useState, useEffect } from 'react';

export const LANGUAGES = [
  { code: 'en', label: 'English', native: 'English' },
  { code: 'hi', label: 'Hindi', native: 'हिन्दी' },
  { code: 'te', label: 'Telugu', native: 'తెలుగు' },
];

export const translations = {
  en: {
    // Brand
    brand_name: 'RaithuSetu',
    brand_subtitle: "Farmer's Friend • Smart Agri",

    // Navbar
    nav_home: 'Home',
    nav_disease: 'Disease Detection',
    nav_market: 'Market Prices',
    nav_schemes: 'Govt Schemes',
    nav_weather: 'Weather',
    nav_community: 'Community',
    nav_login: 'Farmer Login',
    nav_select_lang: 'Select Language / भाषा',
    nav_my_profile: 'My Profile & Farm',
    nav_alerts: 'Alerts & Advisory',
    nav_settings: 'Settings',
    nav_logout: 'Logout',
    nav_join_community: 'Join RaithuSetu community',
    nav_custom_advice: 'Get customized crop advice',
    nav_menu: 'Menu Navigation',

    // Home Page
    hero_badge: 'Next-Gen Smart Agriculture for Indian Farmers',
    hero_title_1: 'Empowering Farmers with',
    hero_title_2: 'Smart Technology',
    hero_desc: 'Diagnose crop diseases instantly with AI, monitor mandi market prices in real-time, access government subsidies, and connect with fellow farmers across India.',
    btn_try_disease: 'Try Disease Detection',
    btn_check_mandi: 'Check Mandi Rates',
    demo_auth_toggle: 'Demo Auth Toggle:',
    card_ai_title: 'AI Crop Doctor',
    card_ai_desc: 'Upload a photo of damaged leaves & get instant diagnosis and pesticide guidance.',
    card_mandi_title: 'Live Mandi Prices',
    card_mandi_desc: 'Track APMC market rates across wheat, rice, cotton, and vegetables daily.',
    card_schemes_title: 'Govt Schemes',
    card_schemes_desc: 'PM-KISAN, crop insurance (PMFBY), tractor subsidies & direct benefit status.',
    card_weather_title: 'Weather Forecast',
    card_weather_desc: 'Hyperlocal 7-day rainfall forecasts and extreme heat advisories for your village.',

    // Disease Detection
    disease_badge: 'AI Plant Pathology Diagnostic Tool',
    disease_title: 'AI Crop Disease Detection',
    disease_desc: 'Upload or take a photo of an affected leaf to identify plant pests and diseases with recommended treatment solutions.',
    upload_box_title: 'Upload Leaf Photograph',
    upload_click: 'Click to browse or drop leaf image',
    upload_hint: 'Supports JPG, PNG, WEBP (Up to 10MB)',
    change_image: 'Click to change image',
    sample_leaves_hint: 'Or test with sample leaves from database:',
    diag_report_title: 'Diagnostic Report',
    diag_analyzing: 'Analyzing your crop leaf with AI...',
    diag_analyzing_sub: 'Evaluating symptoms, pathogen profile & crop safety',
    diag_analyzing_step1: 'Reading image pixels...',
    diag_analyzing_step2: 'Detecting crop type...',
    diag_analyzing_step3: 'Matching disease patterns...',
    diag_analyzing_step4: 'Preparing treatment plan...',
    diag_analyzing_complete: 'Analysis complete!',
    diag_empty: 'Upload a photo to see instant AI diagnosis',
    diag_empty_sub: 'Supports paddy, tomato, chilli, cotton, maize and more',
    match_score: 'Match',
    remedy_organic: 'Organic / Bio-Pesticide Remedy',
    remedy_chemical: 'Recommended Chemical Treatment',
    remedy_prevention: 'Preventive Farming Practices',
    recent_scans: 'Recent Diagnostic Scans',
    ai_confidence_high: 'AI Confidence: High',
    ai_confidence_medium: 'AI Confidence: Medium',
    ai_confidence_low: 'AI Confidence: Low',
    reference_guidance_badge: 'Reference Guidance',
    reference_guidance_desc: 'AI image analysis is temporarily unavailable. The information below is general agricultural reference guidance and is not a confirmed diagnosis.',
    severity_mild: 'Mild',
    severity_moderate: 'Moderate',
    severity_severe: 'Severe',
    severity_unknown: 'Unknown',
    severity_label: 'Severity',
    crop_label: 'Crop',
    disease_label: 'Disease',
    cause_label: 'Cause / Pathogen',
    symptoms_label: 'Identified Symptoms',
    diagnosis_summary_label: 'Diagnosis Summary',
    advisory_warning: 'Advisory & Safety Notice',
    advisory_disclaimer: 'AI-based diagnosis is advisory and should be confirmed by a qualified agricultural extension officer when symptoms are uncertain.',
    chemical_warning: 'Always follow the chemical product label and consult a local agricultural expert for correct dosage and safety intervals.',
    btn_analyzing: 'Analyzing crop leaf...',
    btn_retry_analysis: 'Upload Another Photo',
    source_ai_diagnosis: 'Claude AI Vision',
    source_reference_guidance: 'Reference Guidance',
    invalid_image_msg: 'Please upload a clear photograph of a crop leaf, stem, fruit, or affected plant.',
    insufficient_image_msg: 'The image is not clear enough for reliable diagnosis. Please upload a closer photograph in natural daylight.',
    supported_crops_label: 'Supported Crops',

    // Mandi Prices
    mandi_title: 'Live Mandi & Market Prices',
    mandi_desc: 'Daily real-time modal prices and arrivals from major APMC market yards across India.',
    search_mandi_placeholder: 'Search crop, mandi, district or state...',
    table_commodity: 'Commodity / Crop',
    table_mandi: 'Market (Mandi)',
    table_today_rate: "Today's Rate (₹/Qtl)",
    table_msp: 'Govt MSP',
    table_trend: '24h Trend',
    table_arrival: 'Arrival / Date',
    mandi_loading: 'Fetching live real-time mandi prices...',
    mandi_empty: 'No mandi price records found for the selected filters.',
    mandi_live_badge: 'Govt of India Data.gov.in Live API',

    filter_select_state: 'All States',
    filter_select_crop: 'All Commodities',
    stat_total_commodities: 'Tracked Commodities',
    stat_top_gainer: 'Top Market Gainer',
    stat_msp_coverage: 'Trading Above MSP',
    stat_highest_rate: 'Peak Modal Price',
    badge_above_msp: 'Above MSP',
    badge_near_msp: 'Near MSP',
    badge_below_msp: 'Below MSP',
    price_range_label: 'Price Range',
    variety_label: 'Variety',
    btn_clear_filters: 'Reset Filters',

    // Govt Schemes
    schemes_badge: 'Direct Benefit Transfers & Subsidies',
    schemes_title: 'Government Schemes & Subsidies',
    schemes_desc: 'Check your eligibility, required documents, and apply directly for Central & State agricultural support programs.',
    tab_all: 'All Schemes',
    tab_central: 'Central Scheme',
    tab_insurance: 'Crop Insurance',
    tab_loan: 'Low Interest Loan',
    tab_solar: 'Solar',
    scheme_benefit_label: 'Financial Benefit',
    scheme_eligibility_label: 'Eligibility:',
    scheme_docs_label: 'Required Documents:',
    btn_apply_portal: 'Apply on Official Portal',
    schemes_loading: 'Fetching verified agricultural schemes from database...',

    // Weather
    weather_title: 'Hyperlocal Agro-Weather & Spray Advisory',
    weather_desc: 'Precision weather forecasting tailored for sowing, pesticide spraying, and irrigation schedules.',
    live_village_forecast: 'Live Village Forecast',
    feels_like: 'Feels like',
    uv_index: 'UV Index',
    humidity: 'Humidity',
    wind: 'Wind',
    rain_chance: 'Rain Chance',
    forecast_6day: '6-Day Weather Outlook',
    weather_loading: 'Fetching village weather sensors & agro-advisory...',

    // Community
    community_title: 'RaithuSetu Farmer Community',
    community_desc: 'Connect with 25,000+ farmers, ask questions to agri-scientists, and rent farming machinery locally.',
    your_name_placeholder: 'Your Name (e.g. Ramesh)',
    crop_select_paddy: 'Paddy / Rice',
    crop_select_cotton: 'Cotton',
    crop_select_chilli: 'Chilli',
    crop_select_tomato: 'Tomato',
    crop_select_maize: 'Maize',
    crop_select_groundnut: 'Groundnut',
    crop_select_sugarcane: 'Sugarcane',
    crop_select_banana: 'Banana',
    crop_select_brinjal: 'Brinjal',
    crop_select_potato: 'Potato',
    crop_select_onion: 'Onion',
    crop_select_mango: 'Mango',
    crop_select_other: 'Other',
    crop_select_general: 'General Farming',
    crop_select_machinery: 'Machinery Rental',
    category_label: 'Category',
    cat_crop_problem: 'Crop Problem',
    cat_disease: 'Disease',
    cat_pest: 'Pest',
    cat_irrigation: 'Irrigation',
    cat_fertilizer: 'Fertilizer',
    cat_seeds: 'Seeds',
    cat_market_price: 'Market Price',
    cat_weather: 'Weather',
    cat_govt_scheme: 'Government Scheme',
    cat_machinery: 'Machinery',
    cat_general: 'General Farming',
    cat_other: 'Other',
    location_label: 'Location',
    locality_placeholder: 'Village / Locality (e.g. Anakapalli)',
    district_placeholder: 'District',
    state_placeholder: 'State',
    show_location_label: 'Show my locality on this post',
    post_placeholder: 'Ask a question about crop disease, mandi rate, or post machinery for rent...',
    tag_machinery_rental: 'Tag as Machinery Rental listing',
    btn_post_community: 'Post to Community',
    btn_posting: 'Posting...',
    btn_login_to_post: 'Farmer Login / Sign Up',
    login_required_title: 'Farmer Login Required to Post & Reply',
    login_required_desc: 'Please log in to ask crop questions, reply to fellow farmers, or list machinery for rent.',
    helpful_btn: 'Helpful',
    replies_btn: 'Replies',
    share_btn: 'Share',
    report_btn: 'Report',
    edit_btn: 'Edit',
    delete_btn: 'Delete',
    write_reply_placeholder: 'Write a reply...',
    reply_btn: 'Reply',
    cancel_btn: 'Cancel',
    save_btn: 'Save',
    confirm_delete_post: 'Are you sure you want to delete this post?',
    confirm_delete_reply: 'Are you sure you want to delete this reply?',
    report_reason_label: 'Reason for report',
    report_spam: 'Spam',
    report_misleading: 'Misleading Farming Information',
    report_abusive: 'Abusive Language',
    report_inappropriate: 'Inappropriate Content',
    report_advertisement: 'Advertisement',
    report_scam: 'Scam',
    report_other: 'Other',
    report_submit_btn: 'Submit Report',
    report_success: 'Report submitted. Thank you for helping keep the community safe.',
    failed_report: 'Failed to submit report. Please try again.',
    post_deleted: 'Post deleted successfully.',
    failed_delete_post: 'Failed to delete post. Please try again.',
    reply_deleted: 'Reply deleted.',
    failed_delete_reply: 'Failed to delete reply. Please try again.',
    machinery_created: 'Machinery listing created successfully!',
    failed_create_machinery: 'Failed to create listing. Please try again.',
    failed_update: 'Failed to save. Please try again.',
    report_description_placeholder: 'Additional details (optional)...',
    rental_spotlight_title: 'Village Machinery Sharing',
    rental_spotlight_desc: 'Have a combine harvester, drone sprayer, or tractor sitting idle? Rent it to nearby farmers and earn extra income.',
    btn_list_equipment: 'List Equipment for Rent',
    btn_login_list_equipment: 'Login to List Equipment',
    machinery_section_title: 'Available Farm Machinery',
    machinery_section_desc: 'Machinery available for rent near farmers in your area.',
    machinery_type_label: 'Machine Type',
    machinery_name_label: 'Machine Name',
    machinery_name_placeholder: 'e.g. Mahindra 575 DI Tractor',
    machinery_desc_label: 'Description',
    machinery_price_label: 'Rental Price',
    machinery_price_unit_label: 'Price Unit',
    machinery_availability_label: 'Availability',
    machinery_availability_placeholder: 'e.g. Available on weekdays',
    machinery_contact_label: 'Contact Method',
    machinery_contact_placeholder: 'e.g. Reply on community, call +91...',
    machinery_search_placeholder: 'Search machinery by type or location...',
    per_hour: 'Per Hour',
    per_day: 'Per Day',
    per_acre: 'Per Acre',
    negotiable: 'Negotiable',
    mach_tractor: 'Tractor',
    mach_combine: 'Combine Harvester',
    mach_rotavator: 'Rotavator',
    mach_seed_drill: 'Seed Drill',
    mach_drone: 'Drone Sprayer',
    mach_tiller: 'Power Tiller',
    mach_cultivator: 'Cultivator',
    mach_sprayer: 'Sprayer',
    mach_thresher: 'Thresher',
    mach_other: 'Other',
    filter_all_crops: 'All Crops',
    filter_all_categories: 'All Categories',
    filter_all_locations: 'All Locations',
    filter_newest: 'Newest',
    filter_most_helpful: 'Most Helpful',
    filter_most_discussed: 'Most Discussed',
    search_placeholder: 'Search discussions...',
    loading_posts: 'Loading farmer discussions...',
    error_load_posts: 'Could not load community discussions. Please try again.',
    empty_posts: 'No discussions yet. Be the first farmer to start a conversation!',
    empty_posts_sub: 'Log in and use the form above to post your crop question, problem, or machinery need.',
    empty_machinery: 'No machinery listings yet. Be the first to list your equipment for rent!',
    no_replies_yet: 'No replies yet. Be the first to help!',
    try_again: 'Try Again',
    failed_update: 'Failed to save. Please try again.',
    failed_delete_post: 'Failed to delete post. Please try again.',
    failed_delete_reply: 'Failed to delete reply. Please try again.',
    post_success: 'Your post was published to the farmer community!',
    post_error: 'Failed to create post. Please try again.',
    reply_success: 'Reply posted.',
    reply_error: 'Failed to post reply. Please try again.',
    upload_image: 'Upload Image (optional)',
    image_preview: 'Image preview',
    remove_image: 'Remove image',
    image_too_large: 'Image must be under 5 MB.',
    image_invalid_type: 'Only JPG, JPEG, PNG, WEBP images are allowed.',
    edited_label: 'edited',
    view_all_replies: 'View all replies',
    hide_replies: 'Hide replies',
    load_more: 'Load More Discussions',
    loading_more: 'Loading...',
    nearby_discussions: 'Nearby Discussions',
    community_rules_title: 'Community Rules',
    rule_1: '• Be respectful to all fellow farmers and agri-scientists.',
    rule_2: '• Share genuine farming experiences and honest information.',
    rule_3: '• Do not post spam, scams, or misleading advertisements.',
    rule_4: '• Do not share another farmer\'s private contact information.',
    rule_5: '• Confirm pesticide recommendations with an agricultural expert.',
    tag_rental: 'Machinery Rental',
    badge_official: 'Official',
    badge_verified: 'Verified',
    badge_scientist: 'Scientist',

    // Login & Profile
    login_title: 'Farmer Login',
    login_desc: 'Enter your Email / Gmail to receive an instant verification OTP. Access your land records & subsidies.',
    login_email_label: 'Email / Gmail Address',
    login_email_placeholder: 'farmer@gmail.com',
    mobile_label: 'Mobile Number',
    mobile_placeholder: '98765 43210',
    btn_continue: 'Continue',
    btn_get_otp: 'Continue',
    btn_verify_login: 'Verify & Login',
    btn_continue_guest: '← Continue as Guest',
    enter_otp_label: 'Enter 6-Digit OTP',
    resend_otp_in: 'Resend OTP in',
    btn_resend_otp: 'Resend OTP',
    otp_sent_to: 'OTP sent to',
    profile_tab_overview: 'My Profile',
    profile_tab_alerts: 'Alerts & Advisory',
    profile_tab_settings: 'Settings',
    btn_save_changes: 'Save Changes',
    save_success: 'Profile settings updated successfully!',

    // Footer
    footer_desc: 'Empowering Indian farmers with smart AI crop diagnostics, live mandi rates, and direct scheme access.',
    footer_services: 'Services',
    footer_support: 'Community & Support',
    footer_helpline: 'Kisan Support',
    footer_toll_free: '1800-180-1551 (Toll Free)',
    footer_langs: 'Available in Telugu, Hindi & English',
    footer_copyright: 'RaithuSetu. Dedicated to Indian Farmers.',
    footer_built_with: 'Built with love for Agriculture'
  },

  hi: {
    // Brand
    brand_name: 'रायतु सेतु',
    brand_subtitle: 'किसान मित्र • स्मार्ट कृषि',

    // Navbar
    nav_home: 'होम',
    nav_disease: 'रोग पहचान',
    nav_market: 'मंडी भाव',
    nav_schemes: 'सरकारी योजनाएं',
    nav_weather: 'मौसम',
    nav_community: 'समुदाय',
    nav_login: 'किसान लॉगिन',
    nav_select_lang: 'भाषा चुनें / Select Language',
    nav_my_profile: 'मेरा प्रोफ़ाइल और खेत',
    nav_alerts: 'अलर्ट और सलाह',
    nav_settings: 'सेटिंग्स',
    nav_logout: 'लॉगआउट',
    nav_join_community: 'रायतु सेतु समुदाय से जुड़ें',
    nav_custom_advice: 'व्यक्तिगत फसल सलाह प्राप्त करें',
    nav_menu: 'मेनू नेविगेशन',

    // Home Page
    hero_badge: 'भारतीय किसानों के लिए अगली पीढ़ी की स्मार्ट कृषि',
    hero_title_1: 'किसानों को सशक्त बनाना',
    hero_title_2: 'स्मार्ट तकनीक से',
    hero_desc: 'एआई के साथ तुरंत फसल रोगों का निदान करें, वास्तविक समय में मंडी भाव देखें, सरकारी सब्सिडी प्राप्त करें, और पूरे भारत के किसान भाइयों से जुड़ें।',
    btn_try_disease: 'रोग पहचान आज़माएं',
    btn_check_mandi: 'मंडी भाव देखें',
    demo_auth_toggle: 'डेमो लॉगिन टॉगल:',
    card_ai_title: 'एआई फसल डॉक्टर',
    card_ai_desc: 'प्रभावित पत्तियों की तस्वीर अपलोड करें और तुरंत रोग निदान और कीटनाशक मार्गदर्शन पाएं।',
    card_mandi_title: 'लाइव मंडी भाव',
    card_mandi_desc: 'गेहूं, धान, कपास और सब्जियों के दैनिक एपीएमसी मंडी भाव ट्रैक करें।',
    card_schemes_title: 'सरकारी योजनाएं',
    card_schemes_desc: 'पीएम-किसान, फसल बीमा (PMFBY), ट्रैक्टर सब्सिडी और प्रत्यक्ष लाभ स्थिति।',
    card_weather_title: 'मौसम पूर्वानुमान',
    card_weather_desc: 'अपने गांव के लिए 7-दिवसीय वर्षा पूर्वानुमान और चरम मौसम की सलाह।',

    // Disease Detection
    disease_badge: 'एआई पादप रोग निदान उपकरण',
    disease_title: 'एआई फसल रोग पहचान',
    disease_desc: 'पौधों के कीटों और रोगों की पहचान करने और अनुशंसित उपचार प्राप्त करने के लिए पत्ती की तस्वीर अपलोड करें।',
    upload_box_title: 'पत्ती की तस्वीर अपलोड करें',
    upload_click: 'तस्वीर चुनने के लिए क्लिक करें या यहाँ खींचें',
    upload_hint: 'JPG, PNG, WEBP समर्थित (10MB तक)',
    change_image: 'तस्वीर बदलने के लिए क्लिक करें',
    sample_leaves_hint: 'या डेटाबेस से नमूना पत्तियों से परीक्षण करें:',
    diag_report_title: 'निदान रिपोर्ट',
    diag_analyzing: 'एआई द्वारा फसल की पत्ती का विश्लेषण किया जा रहा है...',
    diag_analyzing_sub: 'लक्षणों, रोगजनक प्रोफ़ाइल और फसल सुरक्षा का मूल्यांकन',
    diag_empty: 'डेटाबेस से तत्काल एआई निदान देखने के लिए एक तस्वीर अपलोड करें',
    match_score: 'सटीकता',
    remedy_organic: 'जैविक / जैव-कीटनाशक उपचार',
    remedy_chemical: 'अनुशंसित रासायनिक उपचार',
    remedy_prevention: 'निवारक कृषि उपाय',
    recent_scans: 'हाल ही के स्कैन',
    ai_confidence_high: 'एआई सटीकता: उच्च (High)',
    ai_confidence_medium: 'एआई सटीकता: मध्यम (Medium)',
    ai_confidence_low: 'एआई सटीकता: कम (Low)',
    reference_guidance_badge: 'संदर्भ मार्गदर्शन',
    reference_guidance_desc: 'एआई छवि विश्लेषण अस्थायी रूप से अनुपलब्ध है। नीचे दी गई जानकारी सामान्य कृषि संदर्भ मार्गदर्शन है और यह पुष्टि किया गया निदान नहीं है।',
    severity_mild: 'हल्का (Mild)',
    severity_moderate: 'मध्यम (Moderate)',
    severity_severe: 'गंभीर (Severe)',
    severity_unknown: 'अज्ञात',
    crop_label: 'फसल',
    disease_label: 'रोग / समस्या',
    symptoms_label: 'पहचाने गए लक्षण',
    diagnosis_summary_label: 'निदान सारांश',
    advisory_warning: 'सलाह व सुरक्षा सूचना',
    advisory_disclaimer: 'एआई निदान केवल सलाहकारी है। लक्षणों में अनिश्चितता होने पर योग्य कृषि विस्तार अधिकारी से परामर्श करें।',
    btn_analyzing: 'पत्ती का विश्लेषण हो रहा है...',
    btn_retry_analysis: 'दूसरी तस्वीर अपलोड करें',
    source_ai_diagnosis: 'क्लाउड एआई विज़न',
    source_reference_guidance: 'संदर्भ मार्गदर्शन',
    invalid_image_msg: 'कृपया फसल की पत्ती, तने या फल की स्पष्ट तस्वीर अपलोड करें।',
    insufficient_image_msg: 'तस्वीर स्पष्ट नहीं है। कृपया प्राकृतिक दिन के उजाले में नज़दीक से ली गई तस्वीर अपलोड करें।',

    // Mandi Prices
    mandi_title: 'लाइव मंडी और बाजार भाव',
    mandi_desc: 'भारत भर के प्रमुख एपीएमसी यार्डों से दैनिक वास्तविक समय मॉडल मूल्य और आवक।',
    search_mandi_placeholder: 'फसल, मंडी, जिला या राज्य खोजें...',
    table_commodity: 'वस्तु / फसल',
    table_mandi: 'मंडी (बाजार)',
    table_today_rate: 'आज का भाव (₹/क्विंटल)',
    table_msp: 'सरकारी एमएसपी',
    table_trend: '24 घंटे का रुझान',
    table_arrival: 'आवक / दिनांक',
    mandi_loading: 'लाइव मंडी भाव लोड हो रहे हैं...',
    mandi_empty: 'चयनित फ़िल्टर के लिए कोई मंडी भाव नहीं मिला।',
    mandi_live_badge: 'भारत सरकार Data.gov.in लाइव API',
    mandi_db_badge: 'रायतु सेतु एपीएमसी डेटाबेस',
    filter_select_state: 'सभी राज्य',
    filter_select_crop: 'सभी फसलें',
    stat_total_commodities: 'ट्रैक की गई फसलें',
    stat_top_gainer: 'शीर्ष बढ़त फसल',
    stat_msp_coverage: 'एमएसपी से अधिक व्यापार',
    stat_highest_rate: 'अधिकतम मॉडल भाव',
    badge_above_msp: 'एमएसपी से अधिक',
    badge_near_msp: 'एमएसपी के करीब',
    badge_below_msp: 'एमएसपी से कम',
    price_range_label: 'मूल्य दायरा',
    variety_label: 'किस्म',
    btn_clear_filters: 'फ़िल्टर हटाएं',

    // Govt Schemes
    schemes_badge: 'प्रत्यक्ष लाभ अंतरण और सब्सिडी',
    schemes_title: 'सरकारी योजनाएं और सब्सिडी',
    schemes_desc: 'अपनी पात्रता, आवश्यक दस्तावेज जांचें और केंद्र एवं राज्य कृषि सहायता कार्यक्रमों के लिए सीधे आवेदन करें।',
    tab_all: 'सभी योजनाएं',
    tab_central: 'केंद्रीय योजनाएं',
    tab_insurance: 'फसल बीमा',
    tab_loan: 'कम ब्याज ऋण',
    tab_solar: 'सोलर पंप',
    scheme_benefit_label: 'वित्तीय लाभ',
    scheme_eligibility_label: 'पात्रता:',
    scheme_docs_label: 'आवश्यक दस्तावेज:',
    btn_apply_portal: 'आधिकारिक पोर्टल पर आवेदन करें',
    schemes_loading: 'डेटाबेस से सरकारी योजनाएं लोड हो रही हैं...',

    // Weather
    weather_title: 'हाइपरलोकल कृषि-मौसम और छिड़काव सलाह',
    weather_desc: 'बुवाई, कीटनाशक छिड़काव और सिंचाई कार्यक्रम के लिए सटीक मौसम पूर्वानुमान।',
    live_village_forecast: 'लाइव गांव का मौसम',
    feels_like: 'अनुभूत तापमान',
    uv_index: 'यूवी इंडेक्स',
    humidity: 'आर्द्रता (नमी)',
    wind: 'हवा की गति',
    rain_chance: 'बारिश की संभावना',
    forecast_6day: '6-दिवसीय मौसम दृष्टिकोण',
    weather_loading: 'मौसम सेंसर और कृषि सलाह प्राप्त की जा रही है...',

    // Community
    community_title: 'रायतु सेतु किसान समुदाय',
    community_desc: '25,000+ किसानों से जुड़ें, कृषि वैज्ञानिकों से प्रश्न पूछें, और स्थानीय स्तर पर कृषि मशीनरी किराए पर लें।',
    your_name_placeholder: 'आपका नाम (उदा. रमेश)',
    crop_select_paddy: 'धान / चावल',
    crop_select_cotton: 'कपास',
    crop_select_chilli: 'मिर्च',
    crop_select_tomato: 'टमाटर',
    crop_select_maize: 'मक्का',
    crop_select_groundnut: 'मूंगफली',
    crop_select_sugarcane: 'गन्ना',
    crop_select_banana: 'केला',
    crop_select_brinjal: 'बैंगन',
    crop_select_potato: 'आलू',
    crop_select_onion: 'प्याज',
    crop_select_mango: 'आम',
    crop_select_other: 'अन्य',
    crop_select_general: 'सामान्य कृषि',
    crop_select_machinery: 'मशीनरी किराया',
    category_label: 'श्रेणी',
    cat_crop_problem: 'फसल समस्या',
    cat_disease: 'रोग',
    cat_pest: 'कीट',
    cat_irrigation: 'सिंचाई',
    cat_fertilizer: 'उर्वरक',
    cat_seeds: 'बीज',
    cat_market_price: 'मंडी भाव',
    cat_weather: 'मौसम',
    cat_govt_scheme: 'सरकारी योजना',
    cat_machinery: 'मशीनरी',
    cat_general: 'सामान्य कृषि',
    cat_other: 'अन्य',
    location_label: 'स्थान',
    locality_placeholder: 'गांव / क्षेत्र (उदा. अनकापल्ली)',
    district_placeholder: 'जिला',
    state_placeholder: 'राज्य',
    show_location_label: 'इस पोस्ट पर मेरा स्थान दिखाएं',
    post_placeholder: 'फसल रोग, मंडी भाव के बारे में प्रश्न पूछें, या किराए के लिए मशीनरी पोस्ट करें...',
    tag_machinery_rental: 'मशीनरी किराया सूची के रूप में टैग करें',
    btn_post_community: 'समुदाय में पोस्ट करें',
    btn_posting: 'पोस्ट किया जा रहा है...',
    btn_login_to_post: 'किसान लॉगिन / साइन अप',
    login_required_title: 'पोस्ट और उत्तर देने के लिए किसान लॉगिन आवश्यक है',
    login_required_desc: 'फसल प्रश्न पूछने, किसान भाइयों को उत्तर देने या मशीनरी सूचीबद्ध करने के लिए लॉगिन करें।',
    helpful_btn: 'मददगार',
    replies_btn: 'जवाब',
    share_btn: 'शेयर करें',
    report_btn: 'रिपोर्ट करें',
    edit_btn: 'संपादित करें',
    delete_btn: 'हटाएं',
    write_reply_placeholder: 'जवाब लिखें...',
    reply_btn: 'उत्तर दें',
    cancel_btn: 'रद्द करें',
    save_btn: 'सहेजें',
    confirm_delete_post: 'क्या आप वाकई इस पोस्ट को हटाना चाहते हैं?',
    confirm_delete_reply: 'क्या आप वाकई इस जवाब को हटाना चाहते हैं?',
    report_reason_label: 'रिपोर्ट का कारण',
    report_spam: 'स्पैम',
    report_misleading: 'भ्रामक कृषि जानकारी',
    report_abusive: 'अभद्र भाषा',
    report_inappropriate: 'अनुचित सामग्री',
    report_advertisement: 'विज्ञापन',
    report_scam: 'धोखाधड़ी',
    report_other: 'अन्य',
    report_submit_btn: 'रिपोर्ट जमा करें',
    report_success: 'रिपोर्ट जमा की गई। समुदाय को सुरक्षित रखने में मदद के लिए धन्यवाद।',
    failed_report: 'रिपोर्ट जमा करने में विफल। कृपया पुनः प्रयास करें।',
    post_deleted: 'पोस्ट सफलतापूर्वक हटा दी गई।',
    failed_delete_post: 'पोस्ट हटाने में विफल। कृपया पुनः प्रयास करें।',
    reply_deleted: 'जवाब हटा दिया गया।',
    failed_delete_reply: 'जवाब हटाने में विफल। कृपया पुनः प्रयास करें।',
    machinery_created: 'मशीनरी सूची सफलतापूर्वक बनाई गई!',
    failed_create_machinery: 'सूची बनाने में विफल। कृपया पुनः प्रयास करें।',
    failed_update: 'सहेजने में विफल। कृपया पुनः प्रयास करें।',
    report_description_placeholder: 'अतिरिक्त विवरण (वैकल्पिक)...',
    rental_spotlight_title: 'ग्राम कृषि उपकरण साझाकरण',
    rental_spotlight_desc: 'क्या आपके पास कंबाइन हार्वेस्टर, ड्रोन स्प्रेयर या ट्रैक्टर उपलब्ध है? इसे नजदीकी किसानों को किराए पर दें और अतिरिक्त आय अर्जित करें।',
    btn_list_equipment: 'किराए के लिए उपकरण सूचीबद्ध करें',
    btn_login_list_equipment: 'उपकरण सूचीबद्ध करने के लिए लॉगिन करें',
    machinery_section_title: 'उपलब्ध कृषि मशीनरी',
    machinery_section_desc: 'आपके क्षेत्र के किसानों के पास किराए के लिए उपलब्ध मशीनरी।',
    machinery_type_label: 'मशीन प्रकार',
    machinery_name_label: 'मशीन का नाम',
    machinery_name_placeholder: 'उदा. महिंद्रा 575 DI ट्रैक्टर',
    machinery_desc_label: 'विवरण',
    machinery_price_label: 'किराया मूल्य',
    machinery_price_unit_label: 'मूल्य इकाई',
    machinery_availability_label: 'उपलब्धता',
    machinery_availability_placeholder: 'उदा. सप्ताह के दिनों में उपलब्ध',
    machinery_contact_label: 'संपर्क विधि',
    machinery_contact_placeholder: 'उदा. समुदाय में उत्तर दें',
    machinery_search_placeholder: 'मशीनरी प्रकार या स्थान से खोजें...',
    per_hour: 'प्रति घंटा',
    per_day: 'प्रति दिन',
    per_acre: 'प्रति एकड़',
    negotiable: 'बातचीत योग्य',
    mach_tractor: 'ट्रैक्टर',
    mach_combine: 'कंबाइन हार्वेस्टर',
    mach_rotavator: 'रोटावेटर',
    mach_seed_drill: 'सीड ड्रिल',
    mach_drone: 'ड्रोन स्प्रेयर',
    mach_tiller: 'पावर टिलर',
    mach_cultivator: 'कल्टीवेटर',
    mach_sprayer: 'स्प्रेयर',
    mach_thresher: 'थ्रेशर',
    mach_other: 'अन्य',
    filter_all_crops: 'सभी फसलें',
    filter_all_categories: 'सभी श्रेणियां',
    filter_all_locations: 'सभी स्थान',
    filter_newest: 'नवीनतम',
    filter_most_helpful: 'सबसे उपयोगी',
    filter_most_discussed: 'सबसे चर्चित',
    search_placeholder: 'चर्चाएं खोजें...',
    loading_posts: 'किसान चर्चाएं लोड हो रही हैं...',
    error_load_posts: 'चर्चाएं लोड नहीं हो सकीं। कृपया पुनः प्रयास करें।',
    empty_posts: 'अभी तक कोई चर्चा नहीं। पहले किसान बनें और बातचीत शुरू करें!',
    empty_posts_sub: 'लॉगिन करें और ऊपर दिए फॉर्म का उपयोग करके अपना फसल प्रश्न या समस्या पोस्ट करें।',
    empty_machinery: 'अभी तक कोई मशीनरी सूची नहीं। पहले अपने उपकरण किराए पर सूचीबद्ध करें!',
    no_replies_yet: 'अभी तक कोई जवाब नहीं। पहले मदद करें!',
    try_again: 'पुनः प्रयास करें',
    failed_update: 'सहेजने में विफल। कृपया पुनः प्रयास करें।',
    failed_delete_post: 'पोस्ट हटाने में विफल। कृपया पुनः प्रयास करें।',
    failed_delete_reply: 'जवाब हटाने में विफल। कृपया पुनः प्रयास करें।',
    post_success: 'आपकी पोस्ट किसान समुदाय में प्रकाशित हो गई!',
    post_error: 'पोस्ट बनाने में विफल। कृपया पुनः प्रयास करें।',
    reply_success: 'जवाब पोस्ट किया गया।',
    reply_error: 'जवाब पोस्ट करने में विफल। कृपया पुनः प्रयास करें।',
    upload_image: 'चित्र अपलोड करें (वैकल्पिक)',
    image_preview: 'चित्र पूर्वावलोकन',
    remove_image: 'चित्र हटाएं',
    image_too_large: 'चित्र 5 MB से कम होना चाहिए।',
    image_invalid_type: 'केवल JPG, JPEG, PNG, WEBP चित्र अनुमत हैं।',
    edited_label: 'संपादित',
    view_all_replies: 'सभी जवाब देखें',
    hide_replies: 'जवाब छुपाएं',
    load_more: 'और चर्चाएं लोड करें',
    loading_more: 'लोड हो रहा है...',
    nearby_discussions: 'आस-पास की चर्चाएं',
    community_rules_title: 'समुदाय के नियम:',
    rule_1: '• सभी किसान भाइयों और कृषि वैज्ञानिकों का सम्मान करें।',
    rule_2: '• वास्तविक खेती के अनुभव और ईमानदारी से जानकारी साझा करें।',
    rule_3: '• स्पैम, धोखाधड़ी या भ्रामक विज्ञापन पोस्ट न करें।',
    rule_4: '• किसी दूसरे किसान की निजी जानकारी साझा न करें।',
    rule_5: '• कीटनाशक सिफारिशें कृषि विशेषज्ञ से पुष्टि करें।',
    tag_rental: 'मशीनरी किराया',
    badge_official: 'आधिकारिक',
    badge_verified: 'सत्यापित',
    badge_scientist: 'वैज्ञानिक',

    // Login & Profile
    login_title: 'किसान लॉगिन',
    login_desc: 'तत्काल ओटीपी प्राप्त करने के लिए अपना ईमेल और मोबाइल नंबर दर्ज करें।',
    login_email_label: 'ईमेल / जीमेल पता',
    login_email_placeholder: 'farmer@gmail.com',
    mobile_label: 'मोबाइल नंबर',
    mobile_placeholder: '98765 43210',
    btn_continue: 'जारी रखें',
    btn_get_otp: 'जारी रखें',
    btn_verify_login: 'सत्यापित करें और लॉगिन करें',
    btn_continue_guest: '← अतिथि के रूप में जारी रखें',
    enter_otp_label: '6-अंकीय ओटीपी दर्ज करें',
    resend_otp_in: 'ओटीपी पुनः भेजें',
    btn_resend_otp: 'ओटीपी दोबारा भेजें',
    otp_sent_to: 'ओटीपी भेजा गया:',
    profile_tab_overview: 'मेरी प्रोफ़ाइल',
    profile_tab_alerts: 'अलर्ट और सलाह',
    profile_tab_settings: 'सेटिंग्स',
    btn_save_changes: 'बदलाव सहेजें',
    save_success: 'प्रोफ़ाइल सेटिंग्स सफलतापूर्वक अपडेट की गईं!',

    // Footer
    footer_desc: 'भारतीय किसानों को स्मार्ट एआई फसल निदान, लाइव मंडी भाव और सीधी योजना पहुंच के साथ सशक्त बनाना।',
    footer_services: 'सेवाएं',
    footer_support: 'समुदाय और सहायता',
    footer_helpline: 'किसान सहायता',
    footer_toll_free: '1800-180-1551 (टोल फ्री)',
    footer_langs: 'तेलुगु, हिंदी और अंग्रेजी में उपलब्ध',
    footer_copyright: 'रायतु सेतु. भारतीय किसानों को समर्पित।',
    footer_built_with: 'कृषि के प्रति समर्पण के साथ निर्मित'
  },

  te: {
    // Brand
    brand_name: 'రైతు సేతు',
    brand_subtitle: 'రైతు మిత్రుడు • స్మార్ట్ వ్యవసాయం',

    // Navbar
    nav_home: 'హోమ్',
    nav_disease: 'రోగ నిర్ధారణ',
    nav_market: 'మార్కెట్ ధరలు',
    nav_schemes: 'ప్రభుత్వ పథకాలు',
    nav_weather: 'వాతావరణం',
    nav_community: 'రైతు వేదిక',
    nav_login: 'రైతు లాగిన్',
    nav_select_lang: 'భాషను ఎంచుకోండి / Select Language',
    nav_my_profile: 'నా ప్రొఫైల్ & పొలం',
    nav_alerts: 'హెచ్చరికలు & సలహాలు',
    nav_settings: 'సెట్టింగ్‌లు',
    nav_logout: 'లాగౌట్',
    nav_join_community: 'రైతు సేతు సంఘంలో చేరండి',
    nav_custom_advice: 'వ్యక్తిగత పంట సలహాలను పొందండి',
    nav_menu: 'మెనూ నావిగేషన్',

    // Home Page
    hero_badge: 'భారతీయ రైతుల కోసం నెక్స్ట్-జెన్ స్మార్ట్ వ్యవసాయం',
    hero_title_1: 'రైతులకు సాధికారత కల్పిస్తూ',
    hero_title_2: 'స్మార్ట్ సాంకేతికతతో',
    hero_desc: 'AI తో తక్షణమే పంట తెగుళ్లు మరియు వ్యాధులను గుర్తించండి, ప్రత్యక్ష మార్కెట్ ధరలను పర్యవేక్షించండి, ప్రభుత్వ సబ్సిడీలను పొందండి మరియు రైతు సోదరులతో అనుసంధానం అవ్వండి.',
    btn_try_disease: 'రోగ నిర్ధారణను ప్రయత్నించండి',
    btn_check_mandi: 'మార్కెట్ ధరలను తనిఖీ చేయండి',
    demo_auth_toggle: 'డెమో లాగిన్ టోగుల్:',
    card_ai_title: 'AI పంట డాక్టర్',
    card_ai_desc: 'దెబ్బతిన్న ఆకుల ఫోటోను అప్‌లోడ్ చేయండి & తక్షణ రోగ నిర్ధారణ మరియు మందుల సలహాలను పొందండి.',
    card_mandi_title: 'ప్రత్యక్ష మార్కెట్ ధరలు',
    card_mandi_desc: 'వరి, పత్తి, మిరప, టమోటా తదితర పంటల రోజువారీ APMC మార్కెట్ ధరలను ట్రాక్ చేయండి.',
    card_schemes_title: 'ప్రభుత్వ పథకాలు',
    card_schemes_desc: 'PM-కిసాన్, పంటల బీమా (PMFBY), ట్రాక్టర్ సబ్సిడీలు మరియు ప్రత్యక్ష ప్రయోజనాల స్థితి.',
    card_weather_title: 'వాతావరణ సూచన',
    card_weather_desc: 'మీ గ్రామానికి సంబంధించిన 7 రోజుల వర్షపాత సూచన మరియు పంట రక్షణ సలహాలు.',

    // Disease Detection
    disease_badge: 'AI మొక్కల రోగ నిర్ధారణ సాధనం',
    disease_title: 'AI పంట తెగులు & రోగ నిర్ధారణ',
    disease_desc: 'తెగులు సోకిన ఆకు ఫోటోను అప్‌లోడ్ చేయండి లేదా ఫోటో తీయండి, తగిన నివారణ మందుల సలహాలను తక్షణమే పొందండి.',
    upload_box_title: 'ఆకు ఛాయాచిత్రాన్ని అప్‌లోడ్ చేయండి',
    upload_click: 'ఫోటో ఎంచుకోవడానికి క్లిక్ చేయండి లేదా ఇక్కడ వేయండి',
    upload_hint: 'JPG, PNG, WEBP ఫార్మాట్లు (10MB వరకు)',
    change_image: 'చిత్రాన్ని మార్చడానికి క్లిక్ చేయండి',
    sample_leaves_hint: 'లేదా డేటాబేస్ నుండి నమూనా ఆకులతో పరీక్షించండి:',
    diag_report_title: 'రోగ నిర్ధారణ నివేదిక',
    diag_analyzing: 'AI తో పంట ఆకును విశ్లేషిస్తోంది...',
    diag_analyzing_sub: 'లక్షణాలు, రోగకారక ప్రొఫైల్ మరియు పంట భద్రతను మూల్యాంకనం చేస్తోంది',
    diag_empty: 'డేటాబేస్ నుండి తక్షణ AI నిర్ధారణను చూడటానికి ఫోటోను అప్‌లోడ్ చేయండి',
    match_score: 'సరిపోలిక',
    remedy_organic: 'సేంద్రీయ / జీవ రసాయన నివారణ',
    remedy_chemical: 'సిఫార్సు చేయబడిన రసాయన మందుల చికిత్స',
    remedy_prevention: 'ముందస్తు పంట సంరక్షణ చర్యలు',
    recent_scans: 'ఇటీవలి రోగ నిర్ధారణలు',
    ai_confidence_high: 'AI ఖచ్చితత్వం: ఎక్కువ (High)',
    ai_confidence_medium: 'AI ఖచ్చితత్వం: మధ్యస్థం (Medium)',
    ai_confidence_low: 'AI ఖచ్చితత్వం: తక్కువ (Low)',
    reference_guidance_badge: 'సూచన మార్గదర్శకత్వం',
    reference_guidance_desc: 'AI చిత్ర విశ్లేషణ తాత్కాలికంగా అందుబాటులో లేదు. క్రింది సమాచారం వ్యవసాయ సూచన మార్గదర్శకత్వం మాత్రమే, ఇది నిర్ధారించబడిన రోగ నిర్ధారణ కాదు.',
    severity_mild: 'తక్కువ (Mild)',
    severity_moderate: 'మధ్యస్థం (Moderate)',
    severity_severe: 'తీవ్రమైనది (Severe)',
    severity_unknown: 'తెలియదు',
    crop_label: 'పంట',
    disease_label: 'వ్యాధి / సమస్య',
    symptoms_label: 'గుర్తించిన లక్షణాలు',
    diagnosis_summary_label: 'నిర్ధారణ సారాంశం',
    advisory_warning: 'భద్రతా సూచన & హెచ్చరిక',
    advisory_disclaimer: 'AI రోగ నిర్ధారణ సలహా రూపంలో మాత్రమే. లక్షణాల్లో ఏవైనా సందేహాలుంటే వ్యవసాయ శాఖ విస్తరణ అధికారిని సంప్రదించండి.',
    btn_analyzing: 'ఆకును విశ్లేషిస్తోంది...',
    btn_retry_analysis: 'మరొక ఫోటో అప్‌లోడ్ చేయండి',
    source_ai_diagnosis: 'క్లాడ్ AI విజన్',
    source_reference_guidance: 'సూచన మార్గదర్శకత్వం',
    invalid_image_msg: 'దయచేసి పంట ఆకు, కాండం లేదా పండు యొక్క స్పష్టమైన ఫోటోను అప్‌లోడ్ చేయండి.',
    insufficient_image_msg: 'చిత్రం తగినంత స్పష్టంగా లేదు. దయచేసి సహజ పగటి వెలుతురులో దగ్గరగా తీసిన ఫోటోను అప్‌లోడ్ చేయండి.',

    // Mandi Prices
    mandi_title: 'ప్రత్యక్ష మార్కెట్ యార్డ్ ధరలు',
    mandi_desc: 'భారతదేశం అంతటా ప్రధాన APMC మార్కెట్ యార్డుల నుండి రోజువారీ మోడల్ ధరలు మరియు రాకలు.',
    search_mandi_placeholder: 'పంట, మార్కెట్, జిల్లా లేదా రాష్ట్రాన్ని వెతకండి...',
    table_commodity: 'వ్యవసాయ పంట / సరుకు',
    table_mandi: 'మార్కెట్ యార్డ్',
    table_today_rate: 'ఈరోజు ధర (₹/క్వింటా)',
    table_msp: 'ప్రభుత్వ మద్దతు ధర (MSP)',
    table_trend: '24 గంటల మార్పు',
    table_arrival: 'రాకలు / తేదీ',
    mandi_loading: 'ప్రత్యక్ష మార్కెట్ ధరలు లోడ్ అవుతున్నాయి...',
    mandi_empty: 'ఎంచుకున్న ఫిల్టర్లకు మార్కెట్ రికార్డులు కనుగొనబడలేదు.',
    mandi_live_badge: 'భారత ప్రభుత్వం Data.gov.in ప్రత్యక్ష API',
    mandi_db_badge: 'రైతు సేతు APMC డేటాబేస్',
    filter_select_state: 'అన్ని రాష్ట్రాలు',
    filter_select_crop: 'అన్ని పంటలు',
    stat_total_commodities: 'ట్రాక్ చేసిన పంటలు',
    stat_top_gainer: 'అత్యధిక లాభం పొందిన పంట',
    stat_msp_coverage: 'MSP కంటే ఎక్కువ ట్రేడింగ్',
    stat_highest_rate: 'అత్యధిక మార్కెట్ ధర',
    badge_above_msp: 'MSP పైన',
    badge_near_msp: 'MSP దగ్గర',
    badge_below_msp: 'MSP కంటే తక్కువ',
    price_range_label: 'ధర శ్రేణి',
    variety_label: 'రకం',
    btn_clear_filters: 'ఫిల్టర్లు తొలగించు',

    // Govt Schemes
    schemes_badge: 'ప్రత్యక్ష ప్రయోజన బదిలీ & సబ్సిడీలు',
    schemes_title: 'ప్రభుత్వ పథకాలు & సబ్సిడీలు',
    schemes_desc: 'మీ అర్హత, అవసరమైన పత్రాలను తనిఖీ చేయండి మరియు కేంద్ర, రాష్ట్ర వ్యవసాయ పథకాలకు నేరుగా దరఖాస్తు చేసుకోండి.',
    tab_all: 'అన్ని పథకాలు',
    tab_central: 'కేంద్ర పథకాలు',
    tab_insurance: 'పంటల బీమా',
    tab_loan: 'తక్కువ వడ్డీ రుణాలు',
    tab_solar: 'సోలార్ పంపులు',
    scheme_benefit_label: 'ఆర్థిక ప్రయోజనం',
    scheme_eligibility_label: 'అర్హత:',
    scheme_docs_label: 'కావలసిన పత్రాలు:',
    btn_apply_portal: 'అధికారిక పోర్టల్‌లో దరఖాస్తు చేయండి',
    schemes_loading: 'డేటాబేస్ నుండి ప్రభుత్వ పథకాలు లోడ్ అవుతున్నాయి...',

    // Weather
    weather_title: 'స్థానిక వ్యవసాయ వాతావరణం & మందుల పిచికారీ సలహా',
    weather_desc: 'విత్తనాలు నాటడం, పురుగుమందుల పిచికారీ మరియు నీటిపారుదల షెడ్యూల్‌ల కోసం ఖచ్చితమైన వాతావరణ సూచన.',
    live_village_forecast: 'ప్రత్యక్ష గ్రామ వాతావరణం',
    feels_like: 'అనిపించే ఉష్ణోగ్రత',
    uv_index: 'UV ఇండెక్స్',
    humidity: 'తేమ శాతం',
    wind: 'గాలి వేగం',
    rain_chance: 'వర్షం అవకాశం',
    forecast_6day: '6 రోజుల వాతావరణ సూచన',
    weather_loading: 'వాతావరణ సెన్సార్లు మరియు సలహాలు లోడ్ అవుతున్నాయి...',

    // Community
    community_title: 'రైతు సేతు చర్చా వేదిక',
    community_desc: '25,000+ రైతులతో మాట్లాడండి, శాస్త్రవేత్తలను ప్రశ్నలు అడగండి మరియు స్థానికంగా వ్యవసాయ యంత్రాలను అద్దెకు తీసుకోండి.',
    your_name_placeholder: 'మీ పేరు (ఉదా. రమేష్)',
    crop_select_paddy: 'వరి',
    crop_select_cotton: 'పత్తి',
    crop_select_chilli: 'మిరప',
    crop_select_tomato: 'టమాట',
    crop_select_maize: 'మొక్కజొన్న',
    crop_select_groundnut: 'వేరుశెనగ',
    crop_select_sugarcane: 'చెరకు',
    crop_select_banana: 'అరటి',
    crop_select_brinjal: 'వంకాయ',
    crop_select_potato: 'బంగాళాదుంప',
    crop_select_onion: 'ఉల్లిపాయ',
    crop_select_mango: 'మామిడి',
    crop_select_other: 'ఇతరాలు',
    crop_select_general: 'సాధారణ వ్యవసాయం',
    crop_select_machinery: 'యంత్రాల అద్దె',
    category_label: 'వర్గం',
    cat_crop_problem: 'పంట సమస్య',
    cat_disease: 'వ్యాధి',
    cat_pest: 'తెగులు / పురుగు',
    cat_irrigation: 'నీటిపారుదల',
    cat_fertilizer: 'ఎరువులు',
    cat_seeds: 'విత్తనాలు',
    cat_market_price: 'మార్కెట్ ధర',
    cat_weather: 'వాతావరణం',
    cat_govt_scheme: 'ప్రభుత్వ పథకం',
    cat_machinery: 'యంత్రాలు',
    cat_general: 'సాధారణ వ్యవసాయం',
    cat_other: 'ఇతరాలు',
    location_label: 'స్థానం',
    locality_placeholder: 'గ్రామం / ప్రాంతం (ఉదా. అనకాపల్లి)',
    district_placeholder: 'జిల్లా',
    state_placeholder: 'రాష్ట్రం',
    show_location_label: 'ఈ పోస్ట్‌లో నా స్థానాన్ని చూపించండి',
    post_placeholder: 'పంట తెగుళ్లు, మార్కెట్ ధరల గురించి అడగండి లేదా అద్దెకు యంత్రాలను పోస్ట్ చేయండి...',
    tag_machinery_rental: 'యంత్రాల అద్దె లిస్టింగ్‌గా ట్యాగ్ చేయండి',
    btn_post_community: 'రైతు వేదికలో పోస్ట్ చేయండి',
    btn_posting: 'పోస్ట్ అవుతోంది...',
    btn_login_to_post: 'రైతు లాగిన్ / సైన్ అప్',
    login_required_title: 'పోస్ట్ చేయడానికి మరియు సమాధానం ఇవ్వడానికి రైతు లాగిన్ అవసరం',
    login_required_desc: 'పంట ప్రశ్నలు అడగడానికి, రైతు సోదరులకు సమాధానం ఇవ్వడానికి లేదా యంత్రాలను జాబితా చేయడానికి లాగిన్ అవ్వండి.',
    helpful_btn: 'ఉపయోగకరం',
    replies_btn: 'సమాధానాలు',
    share_btn: 'షేర్ చేయండి',
    report_btn: 'నివేదించండి',
    edit_btn: 'సవరించండి',
    delete_btn: 'తొలగించండి',
    write_reply_placeholder: 'సమాధానం రాయండి...',
    reply_btn: 'సమాధానం',
    cancel_btn: 'రద్దు చేయండి',
    save_btn: 'సేవ్ చేయండి',
    confirm_delete_post: 'మీరు ఈ పోస్ట్‌ను తొలగించాలనుకుంటున్నారా?',
    confirm_delete_reply: 'మీరు ఈ సమాధానాన్ని తొలగించాలనుకుంటున్నారా?',
    report_reason_label: 'నివేదించడానికి కారణం',
    report_spam: 'స్పామ్',
    report_misleading: 'తప్పుదారి పట్టించే వ్యవసాయ సమాచారం',
    report_abusive: 'అసభ్య భాష',
    report_inappropriate: 'అనుచిత కంటెంట్',
    report_advertisement: 'ప్రకటన',
    report_scam: 'మోసం',
    report_other: 'ఇతరాలు',
    report_submit_btn: 'నివేదిక సమర్పించండి',
    report_success: 'నివేదిక సమర్పించబడింది. సంఘాన్ని సురక్షితంగా ఉంచడంలో సహాయం చేసినందుకు ధన్యవాదాలు.',
    failed_report: 'నివేదిక సమర్పించడంలో విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    post_deleted: 'పోస్ట్ విజయవంతంగా తొలగించబడింది.',
    failed_delete_post: 'పోస్ట్ తొలగించడంలో విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    reply_deleted: 'సమాధానం తొలగించబడింది.',
    failed_delete_reply: 'సమాధానం తొలగించడంలో విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    machinery_created: 'యంత్రాల జాబితా విజయవంతంగా సృష్టించబడింది!',
    failed_create_machinery: 'జాబితా సృష్టించడంలో విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    failed_update: 'సేవ్ చేయడంలో విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    report_description_placeholder: 'అదనపు వివరాలు (ఐచ్ఛికం)...',
    rental_spotlight_title: 'గ్రామ వ్యవసాయ యంత్రాల భాగస్వామ్యం',
    rental_spotlight_desc: 'మీ వద్ద హార్వెస్టర్, డ్రోన్ స్ప్రేయర్ లేదా ట్రాక్టర్ ఉందా? సమీప రైతులకు అద్దెకు ఇచ్చి అదనపు ఆదాయాన్ని సంపాదించండి.',
    btn_list_equipment: 'అద్దె కోసం యంత్రాలను నమోదు చేయండి',
    btn_login_list_equipment: 'యంత్రాలను నమోదు చేయడానికి లాగిన్ అవ్వండి',
    machinery_section_title: 'అందుబాటులో ఉన్న వ్యవసాయ యంత్రాలు',
    machinery_section_desc: 'మీ ప్రాంతంలో రైతులకు అద్దెకు అందుబాటులో ఉన్న యంత్రాలు.',
    machinery_type_label: 'యంత్రం రకం',
    machinery_name_label: 'యంత్రం పేరు',
    machinery_name_placeholder: 'ఉదా. మహీంద్రా 575 DI ట్రాక్టర్',
    machinery_desc_label: 'వివరణ',
    machinery_price_label: 'అద్దె ధర',
    machinery_price_unit_label: 'ధర యూనిట్',
    machinery_availability_label: 'లభ్యత',
    machinery_availability_placeholder: 'ఉదా. వారంలోని రోజులలో అందుబాటులో ఉంది',
    machinery_contact_label: 'సంప్రదింపు పద్ధతి',
    machinery_contact_placeholder: 'ఉదా. సంఘంలో సమాధానం ద్వారా సంప్రదించండి',
    machinery_search_placeholder: 'యంత్రం రకం లేదా స్థానం ద్వారా వెతకండి...',
    per_hour: 'గంటకు',
    per_day: 'రోజుకు',
    per_acre: 'ఎకరానికి',
    negotiable: 'చర్చించదగినది',
    mach_tractor: 'ట్రాక్టర్',
    mach_combine: 'కంబైన్ హార్వెస్టర్',
    mach_rotavator: 'రోటావేటర్',
    mach_seed_drill: 'సీడ్ డ్రిల్',
    mach_drone: 'డ్రోన్ స్ప్రేయర్',
    mach_tiller: 'పవర్ టిల్లర్',
    mach_cultivator: 'కల్టివేటర్',
    mach_sprayer: 'స్ప్రేయర్',
    mach_thresher: 'థ్రెషర్',
    mach_other: 'ఇతరాలు',
    filter_all_crops: 'అన్ని పంటలు',
    filter_all_categories: 'అన్ని వర్గాలు',
    filter_all_locations: 'అన్ని స్థానాలు',
    filter_newest: 'కొత్తవి',
    filter_most_helpful: 'అత్యంత ఉపయోగకరం',
    filter_most_discussed: 'అత్యధిక చర్చించబడినవి',
    search_placeholder: 'చర్చలు వెతకండి...',
    loading_posts: 'రైతు చర్చలు లోడ్ అవుతున్నాయి...',
    error_load_posts: 'చర్చలు లోడ్ చేయలేకపోయింది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    empty_posts: 'ఇంకా చర్చలు లేవు. మొదటి రైతుగా సంభాషణ ప్రారంభించండి!',
    empty_posts_sub: 'లాగిన్ అవ్వండి మరియు పై ఫారమ్‌ని ఉపయోగించి మీ పంట ప్రశ్న లేదా సమస్యను పోస్ట్ చేయండి.',
    empty_machinery: 'ఇంకా యంత్రాల జాబితాలు లేవు. మీ పరికరాలను అద్దెకు జాబితా చేయడానికి మొదటివారు అవ్వండి!',
    no_replies_yet: 'ఇంకా సమాధానాలు లేవు. సహాయం చేయడానికి మొదటివారు అవ్వండి!',
    try_again: 'మళ్ళీ ప్రయత్నించండి',
    failed_update: 'సేవ్ చేయడంలో విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    failed_delete_post: 'పోస్ట్ తొలగించడంలో విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    failed_delete_reply: 'సమాధానం తొలగించడంలో విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    post_success: 'మీ పోస్ట్ రైతు సంఘంలో ప్రచురించబడింది!',
    post_error: 'పోస్ట్ సృష్టించడంలో విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    reply_success: 'సమాధానం పోస్ట్ చేయబడింది.',
    reply_error: 'సమాధానం పోస్ట్ చేయడంలో విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    upload_image: 'చిత్రాన్ని అప్‌లోడ్ చేయండి (ఐచ్ఛికం)',
    image_preview: 'చిత్రం పూర్వదర్శనం',
    remove_image: 'చిత్రాన్ని తొలగించండి',
    image_too_large: 'చిత్రం 5 MB కంటే తక్కువగా ఉండాలి.',
    image_invalid_type: 'JPG, JPEG, PNG, WEBP చిత్రాలు మాత్రమే అనుమతించబడతాయి.',
    edited_label: 'సవరించబడింది',
    view_all_replies: 'అన్ని సమాధానాలు చూడండి',
    hide_replies: 'సమాధానాలు దాచండి',
    load_more: 'మరిన్ని చర్చలు లోడ్ చేయండి',
    loading_more: 'లోడ్ అవుతోంది...',
    nearby_discussions: 'సమీప చర్చలు',
    community_rules_title: 'కమ్యూనిటీ నిబంధనలు:',
    rule_1: '• తోటి రైతు సోదరులను మరియు వ్యవసాయ శాస్త్రవేత్తలను గౌరవించండి.',
    rule_2: '• నిజమైన వ్యవసాయ అనుభవాలు మరియు నిజాయితీగా సమాచారాన్ని పంచుకోండి.',
    rule_3: '• స్పామ్, మోసాలు లేదా తప్పుదారి పట్టించే ప్రకటనలు పోస్ట్ చేయవద్దు.',
    rule_4: '• మరొక రైతు యొక్క వ్యక్తిగత సమాచారాన్ని పంచుకోవద్దు.',
    rule_5: '• పురుగుమందుల సిఫారసులను వ్యవసాయ నిపుణులతో నిర్ధారించుకోండి.',
    tag_rental: 'మశీనరీ అద్దె',
    badge_official: 'అధికారిక',
    badge_verified: 'ధృవీకరించబడింది',
    badge_scientist: 'శాస్త్రవేత్త',

    // Login & Profile
    login_title: 'రైతు లాగిన్',
    login_desc: 'మీ ఖాతాలోకి ప్రవేశించడానికి ఈమెయిల్ మరియు మొబైల్ నంబర్ నమోదు చేసి ఓటీపీని పొందండి.',
    login_email_label: 'ఈమెయిల్ / జీమెయిల్ అడ్రస్',
    login_email_placeholder: 'farmer@gmail.com',
    mobile_label: 'మొబైల్ నంబర్',
    mobile_placeholder: '98765 43210',
    btn_continue: 'కొనసాగండి',
    btn_get_otp: 'కొనసాగండి',
    btn_verify_login: 'ధృవీకరించి లాగిన్ అవ్వండి',
    btn_continue_guest: '← అతిథిగా కొనసాగండి',
    enter_otp_label: '6 అంకెల ఓటీపీని నమోదు చేయండి',
    resend_otp_in: 'ఓటీపీ మళ్ళీ పంపండి',
    btn_resend_otp: 'ఓటీపీ మళ్ళీ పంపండి',
    otp_sent_to: 'ఓటీపీ పంపబడింది:',
    profile_tab_overview: 'నా ప్రొఫైల్',
    profile_tab_alerts: 'హెచ్చరికలు & సలహాలు',
    profile_tab_settings: 'సెట్టింగ్‌లు',
    btn_save_changes: 'మార్పులను సేవ్ చేయండి',
    save_success: 'ప్రొఫైల్ వివరాలు విజయవంతంగా అప్‌డేట్ చేయబడ్డాయి!',


    // Footer
    footer_desc: 'AI పంట రోగ నిర్ధారణ, ప్రత్యక్ష మార్కెట్ ధరలు మరియు ప్రభుత్వ పథకాలతో భారతీయ రైతులకు అండగా రైతు సేతు.',
    footer_services: 'సేవలు',
    footer_support: 'కమ్యూనిటీ & సహాయం',
    footer_helpline: 'కిసాన్ సహాయ కేంద్రం',
    footer_toll_free: '1800-180-1551 (టోల్ ఫ్రీ)',
    footer_langs: 'తెలుగు, హిందీ మరియు ఇంగ్లీషులో అందుబాటులో ఉంది',
    footer_copyright: 'రైతు సేతు. భారతీయ రైతులకు అంకితం.',
    footer_built_with: 'వ్యవసాయంపై ప్రేమతో నిర్మించబడింది'
  }
};


const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [currentLang, setCurrentLang] = useState(
    localStorage.getItem('raithu_lang') || 'en'
  );

  const setLanguage = (langCode) => {
    setCurrentLang(langCode);
    localStorage.setItem('raithu_lang', langCode);
  };

  const t = (key) => {
    const langDict = translations[currentLang] || translations.en;
    return langDict[key] || translations.en[key] || key;
  };

  const activeLangObj =
    LANGUAGES.find((l) => l.code === currentLang) || LANGUAGES[0];

  return (
    <LanguageContext.Provider
      value={{
        language: currentLang,
        setLanguage,
        t,
        activeLangObj,
        languages: LANGUAGES,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
